version: "3"
services:
  server:
    image: shaikfareed/server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
  client:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./
    depends_on:
      - server
    ports:
      - "3000:3000"
